---
all:
  children:
    sql_servers:
      hosts:
        sql2022:
          ansible_host: localhost
          ansible_connection: local
          ds_host: mssql-2022
        sql2025:
          ansible_host: localhost
          ansible_connection: local
          ds_host: mssql-2025

    darling:
      hosts:
        darling-collector:
          ansible_host: localhost
          ansible_connection: local
          ansible_become: true

    grafana:
      hosts:
        grafana:
          ansible_host: localhost
          ansible_connection: local
          grafana_url: http://localhost:3000
